// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqmeKmr020-AkBDjSUpViY8cHjuV1DLOM',
    appId: '1:128274077867:web:4962f3c5cd8cf2e36a7fee',
    messagingSenderId: '128274077867',
    projectId: 'flutter-firebase-codelab-2aa84',
    authDomain: 'flutter-firebase-codelab-2aa84.firebaseapp.com',
    storageBucket: 'flutter-firebase-codelab-2aa84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1PUwE5mtl-NIasXg5Q4uzrhjFg2IjITg',
    appId: '1:128274077867:android:d92d30ff0ab80a066a7fee',
    messagingSenderId: '128274077867',
    projectId: 'flutter-firebase-codelab-2aa84',
    storageBucket: 'flutter-firebase-codelab-2aa84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtwnvFMNiABJOulD89urcdHavlwqcdlPI',
    appId: '1:128274077867:ios:9b1993dbf6bb3daa6a7fee',
    messagingSenderId: '128274077867',
    projectId: 'flutter-firebase-codelab-2aa84',
    storageBucket: 'flutter-firebase-codelab-2aa84.appspot.com',
    iosClientId: '128274077867-0n6dtemtm8p6sv6kqsn69m5gnu6mbfji.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtwnvFMNiABJOulD89urcdHavlwqcdlPI',
    appId: '1:128274077867:ios:3552222245c5e0466a7fee',
    messagingSenderId: '128274077867',
    projectId: 'flutter-firebase-codelab-2aa84',
    storageBucket: 'flutter-firebase-codelab-2aa84.appspot.com',
    iosClientId: '128274077867-47rr5ljfo6ct4u67ehv0r79h4d8gm1ds.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
